// Test harness for PCRE to C++ converter
// Reads JSON input from stdin, runs tokenization, outputs JSON results

#include <iostream>
#include <string>
#include <vector>
#include <sstream>

#include "nlohmann/json.hpp"
#include "unicode.h"

using json = nlohmann::json;

// Forward declaration - this function is generated by pcre_to_cpp.py --name test
std::vector<size_t> unicode_regex_split_test(
    const std::string & text,
    const std::vector<size_t> & offsets
);

// Convert offset list to token strings
std::vector<std::string> offsets_to_tokens(const std::string & text, const std::vector<size_t> & offsets) {
    std::vector<std::string> tokens;
    auto cpts = unicode_cpts_from_utf8(text);

    size_t pos = 0;
    for (size_t offset : offsets) {
        std::string token;
        for (size_t i = 0; i < offset && pos + i < cpts.size(); i++) {
            token += unicode_cpt_to_utf8(cpts[pos + i]);
        }
        tokens.push_back(token);
        pos += offset;
    }

    return tokens;
}

int main() {
    try {
        // Read all input from stdin
        std::stringstream buffer;
        buffer << std::cin.rdbuf();
        std::string input = buffer.str();

        // Parse input JSON
        json input_json = json::parse(input);
        std::vector<std::string> test_strings = input_json["strings"].get<std::vector<std::string>>();

        // Process each string
        json results = json::array();

        for (const std::string & text : test_strings) {
            // Get initial offsets (single chunk = entire text in codepoints)
            auto cpts = unicode_cpts_from_utf8(text);
            std::vector<size_t> initial_offsets = { cpts.size() };

            // Run the generated regex split
            auto result_offsets = unicode_regex_split_test(text, initial_offsets);

            // Convert to tokens
            auto tokens = offsets_to_tokens(text, result_offsets);

            // Add to results
            results.push_back(tokens);
        }

        // Output JSON
        json output;
        output["results"] = results;
        std::cout << output.dump() << std::endl;

        return 0;
    }
    catch (const json::exception& e) {
        std::cerr << "JSON error: " << e.what() << std::endl;
        return 1;
    }
    catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << std::endl;
        return 1;
    }
}
